version: "3.7"
  #version depends on docker engine version: https://docs.docker.com/compose/compose-file/

services:
  #docker container run -d --name server --publish 8761:8761 server
  server:
    image: server:latest
    build: ./server #Either a path to a directory containing a Dockerfile, or a url to a git repository.
    container_name: server
    #expose: - expose for private docker network only. won't be accessible from localhost
    #  - 8761
    ports:
      - "8761:8761"

  client:
    image: client:latest
    build: ./client
    container_name: client
    ports:
      - "8080:8080"
    depends_on:
      - "server"
    environment:
      EUREKA_SERVER: http://server:8761/eureka
