version: "3.7"
  #version depends on docker engine version: https://docs.docker.com/compose/compose-file/

services:
  #docker container run -d --name server --publish 8761:8761 server
  server:
    image: server:latest
    build: ./server #Either a path to a directory containing a Dockerfile, or a url to a git repository.
    container_name: server
    #expose: - expose for private docker network only. won't be accessible from localhost
    #  - 8761
    ports:
      - "8761:8761"

  client:
    image: client:latest
    build: ./client
    container_name: client
    ports:
      - "8080:8080"
    depends_on:
      - "server"
    environment:
      EUREKA_SERVER: http://server:8761/eureka

  profile:
    image: profile:latest
    build: ./profile
    container_name: profile
    ports:
      - "9000:8080"
    depends_on:
      - "server"
    environment:
      EUREKA_SERVER: http://server:8761/eureka

  metadata:
    image: metadata:latest
    build: ./metadata
    container_name: metadata
    ports:
      - "9001:8080"
    depends_on:
      - "server"
    environment:
      EUREKA_SERVER: http://server:8761/eureka

  content:
    image: content:latest
    build: ./content
    container_name: content
    ports:
      - "9002:8080"
    depends_on:
      - "server"
    environment:
      EUREKA_SERVER: http://server:8761/eureka
