version: "3.7"
  #version depends on docker engine version: https://docs.docker.com/compose/compose-file/

services:
  #docker container run -d --name server --publish 8761:8761 server
  server:
    image: server:latest
    build: ./server #Either a path to a directory containing a Dockerfile, or a url to a git repository.
    container_name: server
    #expose: - expose for private docker network only. won't be accessible from localhost
    #  - 8761
    ports:
      - "8761:8761"

  admin:
    image: admin:latest
    build: ./admin
    container_name: admin
    ports:
      - "8082:8080"
    depends_on:
      - "server"
    environment:
      EUREKA_SERVER: http://server:8761/eureka

  client:
    image: client:latest
    build: ./client
    container_name: client
    ports:
      - "8080:8080"
    depends_on:
      - "server"
    environment:
      EUREKA_SERVER: http://server:8761/eureka

  profile:
    image: profile:latest
    build: ./profile
    container_name: profile
    ports:
      - "9000:8080"
    depends_on:
      - "server"
    environment:
      EUREKA_SERVER: http://server:8761/eureka

  metadata:
    image: metadata:latest
    build: ./metadata
    container_name: metadata
    ports:
      - "9001:8080"
    depends_on:
      - "server"
    environment:
      EUREKA_SERVER: http://server:8761/eureka

  content:
    image: content:latest
    build: ./content
    container_name: content
    ports:
      - "9002:8080"
    depends_on:
      - "server"
    environment:
      EUREKA_SERVER: http://server:8761/eureka

  #https://elk-docker.readthedocs.io/
  elk:
    image: sebp/elk:761
    ports:
      - "5601:5601" #kibana
      - "9200:9200" #elastic
      - "5044:5044" #logstash beats filebeat
    environment:
      # https://elk-docker.readthedocs.io/#frequently-encountered-issues
      # https://elk-docker.readthedocs.io/#overriding-variables
      ES_CONNECT_RETRY: 60 # number of seconds to wait for Elasticsearch to be up before starting Logstash and/or Kibana
      MAX_MAP_COUNT: 262144 # limit on mmap counts (default: 65530)
