server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  file:
    path: "/logs"

#logging.level.com.netflix.eureka=OFF
#logging.level.com.netflix.discovery=OFF
