spring:
  application:
    name: 'client'

eureka:
  instance:
    # https://cloud.spring.io/spring-cloud-netflix/multi/multi__service_discovery_eureka_clients.html#_changing_the_eureka_instance_id
#    hostname: ${vcap.application.uris[0]:localhost}
    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 10 # lets the Eureka Server when to check for the health of the client
#    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      # eureka client service URL where client will try to register itself
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

# https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-logging
logging:
  file:
    path: "/logs"
